### ISSUE TITLE
eww widget got deallocated

### ISSUE THREAD

**Issue by FR13NXD** [Aylur/dotfiles#27] opened 2023-06-08 12:26 UTC
my eww logs get spammed with

Caused by:
    Couldn't upgrade reference, widget got deallocated
 2023-06-08T12:25:30.373Z ERROR eww::error_handling_ctx > Error while updating UI after state change

& media player doesnt work

when i run the init:
```
sh $HOME/.config/eww/scripts/init           1 ✘
 2023-06-08T12:36:56.273Z INFO  eww > Initializing Eww server. (/run/user/1000/eww-server_a998a4d5bb250fd2)
Run `eww logs` to see any errors while editing your configuration.
 2023-06-08T12:36:56.275Z INFO  eww::server > Loading paths: config-dir: /home/fr13nd/.config/eww, ipc-socket: /run/user/1000/eww-server_a998a4d5bb250fd2, log-file: /home/fr13nd/.cache/eww_a998a4d5bb250fd2.log

error: referenced unknown widget `desktop`
   ┌─ ./setups/leftbar.yuck:17:49
   │
17 │                         :anchor "bottom right")(desktop))
   │                                                 ─────── Used here



Cache directory: /home/fr13nd/.cache/aylur/

(myshell:465330): Gjs-CRITICAL **: 14:36:56.886: JS ERROR: GLib.SpawnError: Failed to execute child process “eww” (Argument list too long)
_output@file:///home/fr13nd/.config/eww/scripts/myshell/main.js:98:50
vfunc_activate/<@file:///home/fr13nd/.config/eww/scripts/myshell/main.js:71:28
vfunc_activate@file:///home/fr13nd/.config/eww/scripts/myshell/main.js:71:10
App@file:///home/fr13nd/.config/eww/scripts/myshell/main.js:61:14
main@file:///home/fr13nd/.config/eww/scripts/myshell/main.js:133:5
@file:///home/fr13nd/.config/eww/scripts/myshell/myshell:46:5
```

**Comment by FR13NXD** [comment] 2023-06-08 15:12
only the fedora icon to arch linux icon
also discovered this in the logs:

```
Variable not found "main_monitor"
ok
```

**Comment by FR13NXD** [comment] 2023-06-08 15:15
the log spam makes the bar unresponsive etc

**Comment by thyeun** [comment] 2023-06-08 15:33
@FR13NXD look like you not using the latest update. Try to reclone the ```git dotfiles``` again.

**Comment by FR13NXD** [comment] 2023-06-08 15:33
i just reinstalled the dotfiles again

**Comment by thyeun** [comment] 2023-06-08 15:34
@FR13NXD what things not work, can you upload a screenshot to let us see?

**Comment by FR13NXD** [comment] 2023-06-08 15:35
![image](https://github.com/Aylur/dotfiles/assets/127687150/ecce9098-33ae-49ba-a303-1df8e48999f3)
![image](https://github.com/Aylur/dotfiles/assets/127687150/b3cdcc12-7c5b-492a-a1db-a91251c15bb8)
media player doesnt show

**Comment by thyeun** [comment] 2023-06-08 15:37
@FR13NXD For media player, you have to ask @Aylur, his media player work, but my one not working but my one have to manually trigger it.

**Comment by FR13NXD** [comment] 2023-06-08 15:38
how to manualy trigger it?

**Comment by thyeun** [comment] 2023-06-08 15:42
@FR13NXD As you can see the below images, it work with manually trigger for the media player.

For manually trigger, you have to bind a key into you hyprland.conf, as ```bind = $mainMod SHIFT, a, exec, $myshell``` and ```$myshell = $HOME/.config/eww/scripts/myshell/./myshell --eww --file```.

You have to start the media player first, as example, start ```spotify``` and player a song, than manually trigger the ```bind key of myshell```
![Screenshot_2023-05-29-17-04-01_27423](https://github.com/Aylur/dotfiles/assets/1939446/384bce30-9faf-46bd-b370-cf3d855aa673)

**Comment by FR13NXD** [comment] 2023-06-08 15:48
![image](https://github.com/Aylur/dotfiles/assets/127687150/e0a6b56a-f834-41ff-9947-ab14f50e974b)
i ran it while media playing, still didnt apear and i am not missing any depencies, i installed all that are listed in the installation at main page

**Comment by FR13NXD** [comment] 2023-06-08 15:49
and i also use only the eww bar from the dotfiles if it changes anything

**Comment by FR13NXD** [comment] 2023-06-08 15:50
![image](https://github.com/Aylur/dotfiles/assets/127687150/5d93e221-35a3-4731-8eb8-ffba187f04df)
for the depencies i installed all that are here, if something is missing from here, then i am missing in probably

**Comment by thyeun** [comment] 2023-06-08 15:51
@FR13NXD Try this step

1. Relogin until you see the notification icon appear (the white color bell icon)
2. Than start your ```spotify```.
3.  Than manually trigger the ```bind key for myshell```

**Comment by FR13NXD** [comment] 2023-06-08 15:54
cant get the notification icon to appear

**Comment by thyeun** [comment] 2023-06-08 15:56
@FR13NXD mean that your bluetooth also not appear?

**Comment by FR13NXD** [comment] 2023-06-08 15:57
but it doesnt appear

**Comment by thyeun** [comment] 2023-06-08 15:58
@FR13NXD you have to into the ```dependency``` too, install the ```gnome-bluetooth-3.0```, this is one cycle check, if one of it missing, it will stop to continue.

**Comment by thyeun** [comment] 2023-06-08 16:01
@FR13NXD After install, relogin!!!, you re-run ```init``` wont help you to refresh.

**Comment by FR13NXD** [comment] 2023-06-08 16:03
done, still bluetooth icon nowhere

**Comment by thyeun** [comment] 2023-06-08 16:10
@FR13NXD It should be working if every correctly done. (correct dependencies, correct path, and latest git clone).

I can show you my as below with light theme too
![Screenshot_2023-06-07-16-21-55_12555](https://github.com/Aylur/dotfiles/assets/1939446/87d02fa9-5598-44ae-9a91-11408f40aaea)

**Comment by FR13NXD** [comment] 2023-06-08 16:11
![image](https://github.com/Aylur/dotfiles/assets/127687150/f7701e3c-5612-4977-953a-2db6b45c095d)
when i click the change theme icon, it restarts the bar etc and doesnt change the theme

**Comment by thyeun** [comment] 2023-06-08 16:15
@FR13NXD Than you have to ask @Aylur, my one is working fine, only the media player have to manually trigger. =.=

And sorry cant support you.

**Comment by FR13NXD** [comment] 2023-06-08 16:15
well i will try your eww for a second

**Comment by thyeun** [comment] 2023-06-08 16:16
@FR13NXD V2

**Comment by FR13NXD** [comment] 2023-06-08 16:20
![image](https://github.com/Aylur/dotfiles/assets/127687150/ac87df50-0bb5-4559-9dd5-6ed7ff66886c)
nothing

**Comment by FR13NXD** [comment] 2023-06-08 16:21
![image](https://github.com/Aylur/dotfiles/assets/127687150/a783c5a8-b3e0-47b8-bf34-9149e951f9ea)
both dotfiles doesnt show the icons for me

**Comment by FR13NXD** [comment] 2023-06-08 16:21
even the shutdown menu doesnt show

**Comment by thyeun** [comment] 2023-06-08 16:23
@FR13NXD You have to change the ```variables.scss``` i using direct path.

**Comment by FR13NXD** [comment] 2023-06-08 16:26
oh okay now the launcher cat shows up even the power menu, but the media player.

**Comment by thyeun** [comment] 2023-06-08 16:28
@FR13NXD Media player my one you have to manually trigger. Dont run it under terminal, set it into your hyprland key-binding, than trigger it

**Comment by FR13NXD** [comment] 2023-06-08 16:28
![image](https://github.com/Aylur/dotfiles/assets/127687150/035d0a4f-8546-4f8f-9521-46985f7385bf)
also at start, it looks like this, but when i click on the clock, it goes back to transparent background

**Comment by thyeun** [comment] 2023-06-08 16:30
@FR13NXD Do you remove/hide something on your ```init``` file?

**Comment by FR13NXD** [comment] 2023-06-08 16:31
no i didnt

**Comment by thyeun** [comment] 2023-06-08 16:35
@FR13NXD Dont understand why you run init twice?

**Comment by FR13NXD** [comment] 2023-06-08 16:35
because i wanted to show you the error

**Comment by thyeun** [comment] 2023-06-08 16:37
@FR13NXD To show out your error, after you login, you have to run ```gjs -m $HOME/.config/eww/scripts/myshell/./myshell --eww --file```

**Comment by FR13NXD** [comment] 2023-06-08 16:38
@Aylur hello

**Comment by thyeun** [comment] 2023-06-08 16:42
@FR13NXD You are the second one that cant see the media player appear after me. We both no luck to see the media player automatically. =.=

**Comment by FR13NXD** [comment] 2023-06-08 16:44
yeah but i cant even trigger it with your command

**Comment by FR13NXD** [comment] 2023-06-08 16:45
![image](https://github.com/Aylur/dotfiles/assets/127687150/df27a72f-98da-4917-be1f-fca1c197e367)
has to do probably with the eww log

**Comment by thyeun** [comment] 2023-06-08 16:46
@FR13NXD Sometime i also need to relogin one or two times, for seeing the notification icon appear, but this might because of my lousy laptop. Than only manually trigger work.

**Comment by FR13NXD** [comment] 2023-06-08 16:47
is there a way to trigger the notification icon?

**Comment by thyeun** [comment] 2023-06-08 16:49
@FR13NXD Not sure for this, but what i know is, it is a one cycle check, if one of it missing, no matter how many time you manually trigger the media player, it wont show out, have to all the icon show up, than manually trigger only the media player appear.

**Comment by FR13NXD** [comment] 2023-06-08 16:50
couldnt even manually trigger the media player

**Comment by thyeun** [comment] 2023-06-08 16:50
Do you start the spotify before you trigger?

**Comment by FR13NXD** [comment] 2023-06-08 16:50
btw do you know any similar dotfiles that i can use? as i dont think i am able to fix this

**Comment by thyeun** [comment] 2023-06-08 16:53
For hyprland-eww, from what i see on reddit, only @Aylur one is the best, others only OK. i mean easy setup and configuration, others abit hard and some are separated.

**Comment by FR13NXD** [comment] 2023-06-08 16:53
i mean i only care about the bar

**Comment by FR13NXD** [comment] 2023-06-08 16:56
do you know any similar eww bars like this?

**Comment by thyeun** [comment] 2023-06-08 16:57
[dharma](https://github.com/dharmx/vile)

Alot you can find there, but it is separated, you have to combine it, if you want beside the bar

**Comment by FR13NXD** [comment] 2023-06-08 16:58
oh alright

**Comment by FR13NXD** [comment] 2023-06-08 17:06
@thyeun do you know this eww config? https://youtu.be/3P2iqjs0gt4

**Comment by FR13NXD** [comment] 2023-06-08 17:13
@Aylur and also you said that you will make tutorial how to setup the dotfiles in one of your youtube comments, can i just make sure i didnt do anything wrong?

**Comment by thyeun** [comment] 2023-06-08 17:13
@FR13NXD Dont know =.= you have to ask the owner.

**Comment by FR13NXD** [comment] 2023-06-08 17:15
i have now your dotfiles, so you are the owner

**Comment by thyeun** [comment] 2023-06-08 17:22
@FR13NXD i mean the youtube you ask me, i dont know where to find him.

**Comment by FR13NXD** [comment] 2023-06-08 17:23
what

**Comment by thyeun** [comment] 2023-06-08 17:23
https://youtu.be/3P2iqjs0gt4 this one

**Comment by FR13NXD** [comment] 2023-06-08 17:25
oh

**Comment by FR13NXD** [comment] 2023-06-08 17:26
do you have any nice waybars?

**Comment by thyeun** [comment] 2023-06-08 17:34
No, my waybar ugly. waybar alot you can find it at reddit. =.=

**Comment by Aylur** [comment] 2023-06-09 06:44
Your issue is probably with something in `.config/eww/scripts/myshell`, try commenting out stuff you don't need.
This is just how using others dotfiles are, you kind have to figure it out yourself.

**Comment by FR13NXD** [comment] 2023-06-09 07:18
@Aylur .config/eww/scripts/myshell is a directory

**Comment by FR13NXD** [comment] 2023-06-09 07:21
![image](https://github.com/Aylur/dotfiles/assets/127687150/3d8f3c80-4011-4e5e-ad49-c0c69cd1ed3f)
i commented battery and bluetooth as i dont need them, is this what you meant?

**Comment by FR13NXD** [comment] 2023-06-09 09:50
well i reinstalled my operating system, now it works, except battery of cource because i have desktop. i dont know what the problem was but reinstalling my operating system worked for me, means reinstalling all the packages etc, maybe i had wrong version of eww? i dont know

**Comment by FR13NXD** [comment] 2023-06-09 09:50
This seems to be so weird

**Comment by FR13NXD** [comment] 2023-06-09 09:54
well before it was the same story, installed arch, tried it, it worked, after some time it just broke. ill keep this issue updated if it breaks.

**Comment by D3vil0p3r** [comment] 2023-06-10 02:03
I have the same issues:

Selected workspace icon is not filled by white color (not sure if it is expected). Weather data is unavailable. The last two icons at the bottom of the vertical bar report "null" and power buttons icons missing:
![image](https://github.com/Aylur/dotfiles/assets/83867734/3f67a0f7-4636-4e7e-bfc8-c4b7ff0e3cf1)

Furthermore, when clicked on Fedora icon, and the search bar appears, not all applications have their icons despite they should have:
![image](https://github.com/Aylur/dotfiles/assets/83867734/910c8d02-4704-40dc-a073-2a3c3a1007d2)

For example PowerShell is specified by `$HOME/.local.share/applications/powershell.desktop`:
```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=PowerShell
Comment=PowerShell
Icon=/usr/share/icons/hicolor/scalable/apps/powershell.svg
Exec=gnome-terminal -- /usr/bin/bash -c 'pwsh'
Terminal=false
Categories=Tags;Describing;Application
```
and the icon path specified is correct.

Another "issue" is that, when I open a terminal app, like kitty or wezterm, by the application search accessible by Fedora icon, the terminal opens always at `.config/eww` folder instead of HOME.

The last issue I see is that the key combination on my keyboard for decreasing and increasing the volume (`Fn + LeftArrow` and `Fn + RightArrow`) are not caught well by the environment, because, when I press them, the Volume icon appears on the right but the volume level does not change. Instead, if I use the key combination `Fn + UpArrow` and `Fn + DownArrow` for increasing and decreasing screen luminosity, it works well.

**Comment by thyeun** [comment] 2023-06-10 03:06
@D3vil0p3r 

1. For filled up icon, first time using it, it will response slow.
2. For weather, you have to fill up your current location in the weather file. ```~/.config/eww/scripts/weather```
3. For apps icon, it will cache into your ```.cache/aylur/apps``` directory, if you didn see it for the first time, meaning that, it still not in that cache directory. After a few time using your apps from the launcher, you will see it.
4. For the terminal open in directory ```~/.config/eww```, i have the same too. =.=
5. For the volume key, you have to change according to what your need from your ```hyprland.conf```. Due to that this is dotfiles, each of us have our own fav key-bind.

**Comment by Aylur** [comment] 2023-06-10 11:07
The script I wrote for the workspaces just isn't very good.
For the weather you need an OpenWeather api key.
If something is `null` it means the eww variable wasn't set or updated yet, which can be caused by missing dependency or some issue on your specific usecase/setup.
I have no idea why the powermenu icons are missing, you can swap them out for nerd fonts if that works.
The applauncher only loads icons that Gtk.IconTheme can lookup from an icon name and not custom paths to files.
For opening apps I use `gtk-launch` which for some reason I don't know opens the terminal at `.config/eww`.
As for the volume/brightness popup, you should checkout the scripts and figure it out yourself.

**Comment by D3vil0p3r** [comment] 2023-06-10 23:38
Meanwhile I fixed the Audio issue by installing `pipewire-pulse` that will remove `pulseaudio` and then:
```
systemctl --user enable wireplumber
systemctl --user enable pipewire
systemctl --user enable pipewire-pulse
systemctl --user start wireplumber
systemctl --user start pipewire
systemctl --user start pipewire-pulse
```
then reboot.

**Comment by D3vil0p3r** [comment] 2023-06-11 01:53
@Aylur I got the souce of the issue of Powermenu not showing icons. The fault is in `.config/eww/scss/variables.scss`. This file defines a wrong variable for other users different from you, because `assets` variable is defined as:
```scss
$assets: 'home/demeter/.config/eww/assets/';
```
So, all elements using this variable won't work. I don't know if in a `.scss` file is possible to access to env variables as `$HOME`, but it will solve the issue and the icons will appear to the powermenu.

Another issue I found is on `.config/eww/assets` because here there is a broken symbolic link of `wallpaper.png`:
```
lrwxrwxrwx user user  32 B  Sun Jun 11 01:01:22 2023  wallpaper.png@ ⇒ /home/demeter/.config/background
```
and of course the source of this link does not exist. It is better to replace this broken link with the real `wallpaper.png` file.

Could you please fix these things in the repo?

**Comment by Aylur** [comment] 2023-06-11 11:58
> Could be inserting a `cd $HOME` before `gtk-launch` a good idea?

tried `PWD=$HOME gtk-launch` and `cd $HOME && gtk-launch`, but they don't seem to work.

> Then, when I open a terminal and I run `eww reload`, the `null` strings are back:

Because you also need to restart `.config/eww/scripts/myshell/myshell. This is the runtime that updates most eww variables, but it doesn't detect if eww was reloaded.

> I see they are managed in `~/.config/eww/yuck/widgets/bar_widgets.yuck` and they are `{bluetooth.icon}`, `{bluetooth.connected_devices[0].icon}`, `{battery.icon}` and `{notifications.icon}`. Where their source is specifically defined?

in `.config/eww/scripts/myshell/bluetooth.js`

> $assets: 'home/demeter/.config/eww/assets/';

Changed it to `./assets`.

> It is better to replace this broken link with the real `wallpaper.png` file.

That symlink is part of how I change wallpaper, instead of changing it I will just mention it in the readme.

> Also `.local/bin/hypr` has a direct reference to `/home/demeter`. It could be useful for having all of them more generic for all users.

I forgot to remove that file, as I have moved it to home-manager.

**Comment by FR13NXD** [comment] 2023-06-11 14:42
@D3vil0p3r just a question, which polkit agent do you use? give me output of sudo pacman -Q | grep polkit

**Comment by D3vil0p3r** [comment] 2023-06-11 14:44
> @D3vil0p3r just a question, which polkit agent do you use? give me output of sudo pacman -Q | grep polkit

```
polkit 122-1
polkit-gnome 0.105-10
polkit-qt5 0.114.0-1
```
Why this question?

**Comment by FR13NXD** [comment] 2023-06-11 14:45
do you have the polkit running? as i think this may be the issue

**Comment by FR13NXD** [comment] 2023-06-11 14:46
systemctl status polkit-gnome

**Comment by D3vil0p3r** [comment] 2023-06-11 14:47
Which issue in particular are you referring?
```
sudo systemctl status polkit.service
 
● polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static)
     Active: active (running) since Sun 2023-06-11 17:47:01 CEST; 1h 0min ago
       Docs: man:polkit(8)
   Main PID: 800 (polkitd)
      Tasks: 4 (limit: 18908)
     Memory: 6.1M
        CPU: 282ms
     CGroup: /system.slice/polkit.service
             └─800 /usr/lib/polkit-1/polkitd --no-debug

Jun 11 17:47:00 penthost systemd[1]: Starting Authorization Manager...
Jun 11 17:47:01 penthost polkitd[800]: Started polkitd version 122
<SNIP>
```

**Comment by FR13NXD** [comment] 2023-06-11 14:50
i was thinking about it couldnt get the variables because of missing permisions, idk if you understand, try kill polkit-gnome and get polkit-kde-agent and run it

**Comment by D3vil0p3r** [comment] 2023-06-11 14:52
> i was thinking about it couldnt get the variables because of missing permisions, idk if you understand, try kill polkit-gnome and get polkit-kde-agent and run it

Do you mean the issue I have about that icons that sometimes become "null"?

**Comment by FR13NXD** [comment] 2023-06-11 14:53
yes

**Comment by FR13NXD** [comment] 2023-06-11 14:53
like when it fails to get the informations that it should put in there, so it puts null

**Comment by FR13NXD** [comment] 2023-06-11 14:53
because of permisions

**Comment by FR13NXD** [comment] 2023-06-11 14:55
also hyprland (http://wiki.hyprland.org/Useful-Utilities/Must-have/#authentication-agent) recommends polkit-kde-agent, im thinking that they refer to this issue

**Comment by D3vil0p3r** [comment] 2023-06-11 14:59
Y, I will try, even if I was thinking that the explanation of @Aylur is still valid.

**Comment by FR13NXD** [comment] 2023-06-11 15:00
tell me if it worked

**Comment by FR13NXD** [comment] 2023-06-11 15:12
@D3vil0p3r did it work?

**Comment by D3vil0p3r** [comment] 2023-06-11 15:13
Gimme some min. I need to end an activity, it will take 30 min

**Comment by FR13NXD** [comment] 2023-06-11 15:13
alright

**Comment by thyeun** [comment] 2023-06-11 15:19
will this related to the media player appear or not? it sound related too. polkit-gnome and polkit-kde look same to me.

**Comment by FR13NXD** [comment] 2023-06-11 15:20
well for media player and null icons too

**Comment by FR13NXD** [comment] 2023-06-11 15:21
try polkit-kde as hyprland recommends it

**Comment by thyeun** [comment] 2023-06-11 15:30
my setting different, as below 

```
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```

if disable the polkit-gnome, my eww still work, only that media player not show out. =.=

**Comment by FR13NXD** [comment] 2023-06-11 15:33
well i have aylur dotfiles and polkit-kde and media player and all icons show now

**Comment by thyeun** [comment] 2023-06-11 15:38
show me your hyprland.conf setting for the polkit? =.=

**Comment by FR13NXD** [comment] 2023-06-11 15:46
![image](https://github.com/Aylur/dotfiles/assets/127687150/951a9d1e-c6b7-4e3c-ad42-cfcca2da3f67)
(dont ask me why i have the &´s here

**Comment by thyeun** [comment] 2023-06-11 16:07
no different to me.

**Comment by D3vil0p3r** [comment] 2023-06-11 16:31
Same. I have a theory. Here the problem of icons should be related to a race condition issue (I think). When the environment starts, Hyprland Aylur configuration `startup.conf` runs:
```
~/.config/eww/scripts/init
```
This file runs `myshell` script that has the task to set those icons. The content of `init` is:
```bash
#!/usr/bin/env bash

pkill eww
pkill myshell
eww daemon
 
# HDMI=$(hyprctl monitors -j | jq .[1].name)
# if [[ $HDMI == '"HDMI-A-1"' ]]; then
#     # open both monitor stuff
# else
#     # open main monitror stuff
# fi

eww open bar
# eww open dock
eww open desktop
eww open notifications_popup
# eww inspector

$HOME/.config/eww/scripts/myshell/./myshell --eww --file
```
So, it runs the eww daemon, open the elements of our desktop, and at the end runs `myshell --eww --file`. Normally, when `myshell` is run, it should set icons.

If you go now, after the initialization, to run `myshell --eww --file` you could get:
```
Cache directory: /home/myuser/.cache/aylur/
Another Notification Daemon is already running!
```
Since `myshell` is run at the end of `init`, it means one thing imho:

Sometimes myshell is able to run because there is no this "Another Notification Daemon" so it can run cleanly and set the icons. Other times, during the initialization, this strange "Notification Daemon" starts before myshell is running, and it causes myshell to get that message, so it cannot run and cannot set the icons. @Aylur my theory is right?

**Comment by thyeun** [comment] 2023-06-11 16:41
@D3vil0p3r Totally agree, that is the reason i have to manually trigger ```myshell``` again. it should trigger after everything finish (let make it everything finish as one cycle), but some how, this so call one cycle cant finish it, than something been trigger early.

**Comment by D3vil0p3r** [comment] 2023-06-11 16:41
Another problem Im getting often is: when I open the App Launcher (by Super + R), and it appears on the center, sometimes I search for an application, for example Brave browser, and when I double click on it, the application opens, but the application launcher window does not, it remains opened, even if I change workspace and if I try to killactive, it remains. I can open other apps by it but the focus remains on the application launcher and my only solution is to reboot. Did you get at least one time this strange behavior? It happens to me often.

**Comment by thyeun** [comment] 2023-06-11 16:45
@D3vil0p3r For the apps, yes, i get it also, but for me, it might because my old laptop less RAM issue, that why i didn care it so much.

my laptop still is ```Intel Gen-2``` with ```8Gb RAM```. =.= hehehehehe

**Comment by D3vil0p3r** [comment] 2023-06-11 16:47
> @D3vil0p3r For the apps, yes, i get it also, but for me, it might because my old laptop less RAM issue, that why i didn care it so much.
> 
> my laptop still is ```Intel Gen-2``` with ```8Gb RAM```. =.= hehehehehe

I dont think it is due to your old laptop. I have a MSI GL63 laptop that is good in performance (with an Intel Integrated GPU and NVIDIA RTX) and 8 GB of RAM.

**Comment by Aylur** [comment] 2023-06-11 16:50
I don't think polkit has anything to do with this.
`myshell` is a notification daemon aswell, and running it twice is not handled so if you run it twice you will get `Another Notification Daemon is already running!` because another instance of `myshell` is already running.
There is no race condition. The `init` script is sequential not concurrent, `eww` is already running when `myshell` is launched.
You can check this behaviour by
```bash
#run the init
~/.config/eww/scripts/init
#check state, everything should be set
eww state
#reload eww
eww reload
#check state and see that the variables were reset
eww state
#if you run myshell again, it will not function as expected, because there is another instance already running
#this should output the Another Notification Daemon is already running! message
~/.config/eww/scripts/myshell/myshell
```

if you have any issue just run the `init` script. It will reload everything and you will see the logs if there is any problem.

**Comment by thyeun** [comment] 2023-06-11 16:51
@D3vil0p3r But it not happen to all people that been using, only me until now, my media player from beginning till today, never ever appear one time. =.=

**Comment by thyeun** [comment] 2023-06-11 16:53
@Aylur No issue inside log file until today. that why i blame my old laptop, not perform well. hehehehe

**Comment by Aylur** [comment] 2023-06-11 16:55
> Another problem Im getting often is: when I open the App Launcher (by Super + R), and it appears on the center, sometimes I search for an application, for example Brave browser, and when I double click on it, the application opens, but the application launcher window does not close itself, it remains opened, even if I change workspace and if I try to killactive, it remains. I can open other apps by it but the focus remains on the application launcher and my only solution is to reboot. Did you get at least one time this strange behavior? It happens to me often.

`killactive` won't do anything, because it is a layershell window not a regular one.
If you click outside of the box it should disappear or if you hit enter while the entry has focus it should launch the first app in the list then close the window.
I can't make it disappear when ESC is pressed, it is just a limitation of Eww.

**Comment by thyeun** [comment] 2023-06-11 16:59
@Aylur can the dbus of mpris.mediaplayer, keep refresh till it find a player (run it at the background)?

**Comment by Aylur** [comment] 2023-06-11 17:06
> @Aylur can the dbus of mpris.mediaplayer, keep refresh till it find a player (run it at the background)?

I am not sure what you are reffering to.
If you first launch `myshell` it will run a query of the available dbus interfaces and if it finds an mpris one it will attach to it. After this it will start listening on the `/org/freedesktop/DBus` which will signal if an mpris interface appeared or disappeared. There is no polling it is all event based.

**Comment by thyeun** [comment] 2023-06-11 17:16
@Aylur Image below

![Screenshot_2023-06-12-01-14-56_13371](https://github.com/Aylur/dotfiles/assets/1939446/faa79a35-22e9-47a9-9020-941cb061fd1a)

**Comment by thyeun** [comment] 2023-06-11 17:17
@Aylur It can continue to run ```eww get media | jg```, i have to ```ctrl + c``` only can continue

**Comment by Aylur** [comment] 2023-06-11 17:27
if you `ctrl+c` you kill the running `myshell` process that is why I said to open another terminal, but its good enough.
Anyway, your issue is still with the app_launcher. `Gjs-CRITICAL` means that parts of the code will not run.

**Comment by Aylur** [comment] 2023-06-11 17:28
Pull my commit and try again.

**Comment by thyeun** [comment] 2023-06-11 17:28
The log file will keep increase till now 30Gb, after i try the step as you mentioned

**Comment by thyeun** [comment] 2023-06-11 17:34
@Aylur I love you so much, the media player now working and appear automatically, and play-pause also change the icon accordingly.

**Comment by D3vil0p3r** [comment] 2023-06-11 19:34
> > Another problem Im getting often is: when I open the App Launcher (by Super + R), and it appears on the center, sometimes I search for an application, for example Brave browser, and when I double click on it, the application opens, but the application launcher window does not close itself, it remains opened, even if I change workspace and if I try to killactive, it remains. I can open other apps by it but the focus remains on the application launcher and my only solution is to reboot. Did you get at least one time this strange behavior? It happens to me often.
> 
> `killactive` won't do anything, because it is a layershell window not a regular one. If you click outside of the box it should disappear or if you hit enter while the entry has focus it should launch the first app in the list then close the window. I can't make it disappear when ESC is pressed, it is just a limitation of Eww.

It is stucked there, because even if I click outside of the box or hit enter, it does not focus on the other windows and it remains opened. If you want to try to test it, try to press `CTRL + R`, sometimes launch an application, press again `CTRL + R` e try to close it.

**Comment by Aylur** [comment] 2023-06-11 23:49
What is the output of `eww logs` and `~/.config/eww/scripts/init` when this occurs?

**Comment by FR13NXD** [comment] 2023-06-13 03:50
@D3vil0p3r as the fi in the media player, i think i know why the issue, you probably removed eww open desktop or something from eww/scripts/init, as it happened to me when i removed that eww open desktop

**Comment by FR13NXD** [comment] 2023-06-13 03:51
i dont know why it broke media player but alright

**Comment by thyeun** [comment] 2023-06-13 09:31
@FR13NXD the ```fi``` appear on the media player, it is codepoint error from ```ubuntu nerd font```. You can change that on the file ```main.js```. On this line ```'deafult': '',``` change the music icon to the correct codepoint from nerd font cheatsheet.

**Comment by thyeun** [comment] 2023-06-13 12:29
Let me further explain this.

1. ```deafult``` - is something you can use like```vlc```, it will fall into this group.
2.  ```spotify``` - it is make it only for ```spotify```.
3.  ```firefox``` - ```librewolf``` also fall into this group.
4.  ```mpv``` - any that play under ```mpv``` will fall into this group.

you can add extra, but make sure the WM_class or app-ID are same, and you have to add-in some color into the ```scss```

my ```main.js```
```
export const PlayerIcons = {
    'deafult': '󰎆',
    'spotify': '',
    'firefox': '󰈹',
    'mpv': ''
}
```

And my color for each player inside ```bar_widget.scss```
```
.icon{
        &.vlc{ color: $yellow; }
        &.spotify{ color: $green; }
        &.firefox{ color: $orange; }
        &.mpv{ color: $magenta; }
    }
```

**Comment by FR13NXD** [comment] 2023-06-13 12:43
so when i add some app id, and icon for it and css, it should work and everything will be fine r

**Comment by thyeun** [comment] 2023-06-13 12:46
make sure it is mpris protocol too. =.=

**Comment by D3vil0p3r** [comment] 2023-06-13 18:33
> What is the output of `eww logs` and `~/.config/eww/scripts/init` when this occurs?

For reproducing the issue, I just hit `SUPER + R` multiple times. After the event of the issue, `eww logs` does not produce additional logs, but it stays with the following info:
```
 2023-06-11T15:19:19.728Z ERROR eww::error_handling_ctx > The script for the `volume`-variable exited unsuccessfully
 2023-06-11T15:19:22.724Z ERROR eww::error_handling_ctx > The script for the `brightness`-variable exited unsuccessfully
 2023-06-11T15:19:22.731Z ERROR eww::error_handling_ctx > The script for the `volume`-variable exited unsuccessfully
 2023-06-11T15:19:25.732Z ERROR eww::error_handling_ctx > The script for the `brightness`-variable exited unsuccessfully
 2023-06-11T15:19:25.735Z ERROR eww::error_handling_ctx > The script for the `volume`-variable exited unsuccessfully
 2023-06-11T15:19:25.953Z INFO  eww::server             > Shutting down eww daemon...
 2023-06-11T15:19:25.953Z INFO  eww::app                > Received kill command, stopping server!
 2023-06-11T15:19:25.953Z INFO  eww::app                > Closing gtk window notifications_popup
 2023-06-11T15:19:25.953Z INFO  eww::app                > Closing gtk window desktop
 2023-06-11T15:19:25.953Z INFO  eww::app                > Closing gtk window bar
```
The content of `~/.config/eww/scripts/init` is:
```
#!/usr/bin/env bash

pkill eww
pkill myshell
eww daemon
 
# HDMI=$(hyprctl monitors -j | jq .[1].name)
# if [[ $HDMI == '"HDMI-A-1"' ]]; then
#     # open both monitor stuff
# else
#     # open main monitror stuff
# fi

eww open bar
# eww open dock
eww open desktop
eww open notifications_popup
# eww inspector

$HOME/.config/eww/scripts/myshell/./myshell --eww --file
```
The keybinding of `SUPER + R` is:
```
bind = SUPER, R, exec, bash ~/.config/eww/scripts/launcher toggle_menu app_launcher
```
So, there should be some weird element that could create my issue in:
```
function toggle_menu {
    MAIN=$(eww get main_monitor)
    hyprctl keyword blurls "remove,gtk-layer-shell"
    STATE=$(eww windows | grep $1$MAIN | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE == '*' ]]; then 
        if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "remove,gtk-lay>
        eww close $1$MAIN;
    else
        if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "gtk-layer-shel>
        if [[ $1 == 'app_launcher' ]]; then $HOME/.config/eww/scripts/apps quer>
        eww open $1$MAIN;
    fi
}
```

**Comment by thyeun** [comment] 2023-06-14 03:19
Not sure what you all facing. But my ```log``` file always stay as empty even that time the media player not appear.
![Screenshot_2023-06-14-11-14-12_19100](https://github.com/Aylur/dotfiles/assets/1939446/aaea1b8a-af7a-4006-9f9e-a8ad0fcd9099)

**Comment by thyeun** [comment] 2023-06-14 03:24
@D3vil0p3r Are you using ```rofi``` or ```wofi```? if you using ```wofi```, from the ```launcher``` file, you have to change the line
```if [[ $1 == 'app_launcher'    ]]; then wofi --show drun; fi``` 

And for the ```main_monitor```, try change the line ```MAIN=$(eww get main_monitor)``` to ```MAIN = ""```, see any help on that.

**Comment by D3vil0p3r** [comment] 2023-06-15 15:36
> @D3vil0p3r Are you using `rofi` or `wofi`? if you using `wofi`, from the `launcher` file, you have to change the line `if [[ $1 == 'app_launcher' ]]; then wofi --show drun; fi`
> 
> And for the `main_monitor`, try change the line `MAIN=$(eww get main_monitor)` to `MAIN = ""`, see any help on that.

I didn't customize the original files of the repo so I don't know if it uses wofi or rofi. Btw I also changed "MAIN" value but my issue is still there.

Then, what I noted is that, `CTRL+C` combination that is used for interrupting command execution is not working on this theme despite it is not overridden in the keybind file.

Furthermore, I note that, when I replicate the issue I explained in my previous comment and then I reboot, after reboot, I have two vertical bars...
![image](https://github.com/Aylur/dotfiles/assets/83867734/39dd5268-3253-4408-bc3f-97bb99b5f12c)

**Comment by thyeun** [comment] 2023-06-15 17:18
@D3vil0p3r You have to modify the ```variable.scss```file according to your correct path, and change the ```wallpaper.png``` or replace it, it is symlink that the reason your kitty not show inside your launcher. =.= 

```fi``` in the launcher same case as the media player icon that show ```fi```, it is codepoint error from ```ubuntu nerd font```. you have to replace it from the nerd font cheatsheet with the correct one in the file ```app_launcher.yuck```

**Closed** 2023-06-30 00:29 UTC
