### ISSUE TITLE
Menu Click issue

### ISSUE THREAD

**Issue by Lanpingner** [Aylur/dotfiles#124] opened 2023-12-19 12:13 UTC
Hi There
I am having an issue maybe someone else also faced it when i click on a menu item directly in the middle its not working
![WhatsApp Image 2023-12-19 at 13 10 24](https://github.com/Aylur/ags/assets/45770525/a01a4302-b957-4830-a26a-f90634714af8)
Like this

However if i click on the menu bottom part its works looks like i need to offset the mouse position same size as the bar
Like this :
![WhatsApp Image 2023-12-19 at 13 10 35](https://github.com/Aylur/ags/assets/45770525/a59998ff-0fd0-4962-8ba0-f73a4ee1090b)

I am using your config with some small tweeks only in the widgets

**Comment by Aylur** [comment] 2023-12-19 12:19
duplicate of #104

**Closed by Aylur** 2023-12-19 12:19 UTC
