### ISSUE TITLE
Ags bar is not showing

### ISSUE THREAD

**Issue by Sitolam** [Aylur/dotfiles#214] opened 2024-04-07 16:07 UTC
If I manually run the command `ags` from the terminal it gives me this error: 
```bash
(com.github.Aylur.ags:40650): Gjs-Console-CRITICAL **: 18:06:32.653: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
@file:///tmp/ags/main.js:513:21
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Aylur** [comment] 2024-04-07 16:11
duplicate of #211

**Closed by Aylur** 2024-04-07 16:11 UTC
